ruby '2.2.0'

source 'https://rubygems.org'

gem 'roda'
gem 'roda-rest_api'
gem 'slim'
gem 'multi_json'
gem 'oj'
gem 'puma'
gem 'activesupport'
gem 'sqlite3'
gem 'rom', github: 'rom-rb/rom'
gem 'rom-sql', github: 'rom-rb/rom-sql'
gem 'virtus'

group :development, :test do
  gem 'rspec'
end
