ruby '2.2.1'

source 'https://rubygems.org'

gem 'roda'
gem 'roda-rest_api'
gem 'thin' #ember proxy has problem with puma, since puma bind into tcp:// :(
gem 'activesupport'
gem 'rom', github: 'rom-rb/rom'
gem 'rom-sql', github: 'rom-rb/rom-sql'
gem 'virtus'

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'sqlite3'
  gem 'rspec'
  gem 'rack-test'
end
