require 'bundler/setup'
require 'rom'
require 'rom/sql'
require 'rom/sql/rake_task'
require_relative 'db/db'

namespace :db do
  task :load_setup do
    ROM::SQL::Migration.connection = DB.connection
    ROM::SQL::Migration.path = 'db/migrations'
  end
end
